name: CalledWorkflow

on:
 repository_dispatch:
  types: [CalledWorkflow]

jobs:
  
   build:
    
     runs-on: ubuntu-latest
     env:
        parameter1: ${{ github.events.client_payload.parameter1 }}
        parameter2: ${{ github.events.client_payload.parameter1 }}

     steps:

     - uses: action/checkout@v3

     - name: Run a one-line script
       run: echo Custom Workflow!

     - name: Run a multi-line script
       run: |
          echo Add other actions to build,
          echo test and deploy your project,
          echo $parameter1,
          echo $parameter2    